# Generated by Django 3.0.3 on 2020-05-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bloodGrp',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialist',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Active'), ('2', 'Inactive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodGrp',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=20),
        ),
    ]
