# Generated by Django 3.0.3 on 2020-05-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20200523_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doc',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
    ]
