# Generated by Django 3.0.3 on 2020-05-23 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20200523_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
