# Generated by Django 3.0.3 on 2020-05-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20200524_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='outstanding',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
