# Generated by Django 3.0.3 on 2020-05-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_patient_outstanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
