# Generated by Django 3.0.3 on 2020-05-24 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_prescription_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.IntegerField(blank=True, default=0)),
                ('outstanding', models.IntegerField(blank=True, default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
