# Generated by Django 3.0.3 on 2020-05-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_p_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='outstanding',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='paid',
        ),
    ]
